// ─────────────────────────────────────────────────────────────
// The hundred worlds.
//
// Each entry is a configuration, not a copy: it names an engine, the
// substrate and motion that make its own sense of time, a palette, the
// gesture that closes it, the mark it keeps afterwards, and two cues
// from one timbre family — one for the world starting, one for it
// entering its last minute.
// ─────────────────────────────────────────────────────────────

import { cue, N, FAMILIES } from './cues.js';

/** Palette: deep ground, soft ground, material, accent, spark. */
const P = (h, s, o = {}) => {
  const a = (h + (o.a ?? 24) + 360) % 360;
  const k = (h + (o.k ?? 46) + 360) % 360;
  const L = o.light;
  return [
    [h, L ? 12 : Math.min(s, 42), L ? (o.bg ?? 93) : (o.bg ?? 4.5)],
    [h, L ? 9  : Math.min(s, 34), L ? (o.bg2 ?? 87) : (o.bg2 ?? 9.5)],
    [h, Math.round(s * 0.72),     L ? (o.mid ?? 46) : (o.mid ?? 44)],
    [a, s,                        L ? 38 : (o.acc ?? 56)],
    [k, Math.min(s + 12, 96),     L ? 46 : (o.spk ?? 70)]
  ];
};

/** Two cues from the same family: the world opening, and its last minute. */
const S = (fam, startNotes, lastNotes, o = {}) => ({
  start: cue(fam, startNotes.map(N), { spread: o.s ?? 175, ...(o.so || {}) }),
  last:  cue(fam, lastNotes.map(N),  { spread: o.l ?? 150, gain: FAMILIES[fam].gain * 1.14, ...(o.lo || {}) })
});

const D = (id, name, engine, prm, pal, comp, mark, sound, meta) =>
  ({ id, name, engine, prm, pal, completion: comp, mark, sound, meta });

export const DESIGNS = [

// ══ 01–10 ════════════════════════════════════════════════════
D('fog-atlas', 'Fog Atlas', 'fog',
  { substrate: 'contour', sweep: 'diagonal', layout: 'scatter', density: 86, ridges: 5, soft: 0.13, headSize: 0.34, scale: 1.1 },
  P(205, 30, { a: -16, k: 40 }),
  { type: 'trace', affordance: '晴れた地形に描きかけの等高線があらわれる', feedback: 'なぞった範囲だけ線が温かく光り、霧が後退する' },
  'contourTriple',
  S('air', [-9, 4], [0, 7, 0], { s: 190, l: 165 }),
  { elapsed: '霧が晴れ、川と等高線が読める', current: '霧を切り開く細い光', remaining: '厚い霧の底' }),

D('tidal-manuscript', 'Tidal Manuscript', 'trail',
  { scenery: 'stone', mark: 'ripple', agent: 'dot', knots: 8, marks: 54, field: 34, routeWidth: 1.2, headSize: 0.13 },
  P(38, 26, { a: 170, k: 186, mid: 52 }),
  { type: 'drag', affordance: '砂浜に小さな貝殻があらわれる', feedback: '貝殻の移動に合わせて砂紋が整う' },
  'spiral',
  S('water', [-5, 7], [7, 7, 11], { s: 165, l: 145 }),
  { elapsed: '線と渦の描かれた砂', current: '白い波の先端', remaining: '何も描かれていない砂浜' }),

D('shadow-orchard', 'Shadow Orchard', 'fog',
  { substrate: 'grove', sweep: 'columns', layout: 'rows', density: 54, soft: 0.1, headSize: 0.3, scale: 1.15, sway: 1.2 },
  P(96, 30, { a: -54, k: -70, mid: 40 }),
  { type: 'hold', affordance: '葉の形をした光が一枚のこる', feedback: '押し続けるほど葉脈が整い、影が静止する' },
  'leafVein',
  S('wood', [-12, 0], [0, 4], { s: 150, l: 130 }),
  { elapsed: '影の向きと地面の模様が変わった果樹園', current: '果樹園を横切る暖かい日差し', remaining: '長く冷たい影' }),

D('under-ice', 'Under-Ice Meridian', 'fog',
  { substrate: 'ice', sweep: 'diagonal', layout: 'scatter', density: 64, soft: 0.11, headSize: 0.26, scale: 1.3 },
  P(192, 34, { a: 14, k: 30, mid: 52 }),
  { type: 'join', affordance: '離れた二本の亀裂の端があらわれる', feedback: '近づくほど氷の内部に結晶模様が広がる' },
  'crystal6',
  S('glass', [7, 19], [12, 14], { s: 200, l: 170 }),
  { elapsed: '透明度が上がり、下の水と泡が見える', current: '亀裂を流れる淡い光', remaining: '白く濁った氷' }),

D('rainfront-city', 'Rainfront City', 'fog',
  { substrate: 'city', sweep: 'columns', layout: 'rows', density: 66, soft: 0.07, headSize: 0.24, scale: 1.0 },
  P(216, 32, { a: 26, k: 34, mid: 40 }),
  { type: 'drag', affordance: '窓の大きな雨粒と路面の琥珀色の反射', feedback: '雨粒の位置に応じて路面反射が一本の線へ整う' },
  'reflectLine',
  S('water', [-2, 10], [10, 10, 15], { s: 150, l: 140 }),
  { elapsed: '濡れて光を反射する街', current: '雨のカーテンの境界', remaining: '乾いたままの街' }),

D('dune-resonance', 'Dune Resonance', 'lines',
  { axis: 'v', density: 30, weight: 1.6 },
  P(32, 30, { a: 14, k: 30, mid: 48 }),
  { type: 'trace', affordance: '短い砂紋が一本だけ途切れている', feedback: 'なぞった場所から砂粒の影が整列する' },
  'contourTriple',
  S('air', [-10, 2], [2, 9, 2], { s: 185, l: 160 }),
  { elapsed: '角度と密度の変わった砂紋', current: '移動する風の境界', remaining: '一方向のままの砂紋' }),

D('biolum-cavern', 'Bioluminescent Cavern', 'swarm',
  { count: 110, spread: 0.2, settle: 'glowdot', knots: 7 },
  P(172, 44, { a: 30, k: 44, mid: 40 }),
  { type: 'hold', affordance: '最後の発光生物の群れ', feedback: '群れが徐々に密集し、光が岩壁へ移る' },
  'rosette',
  S('glass', [-5, 4], [4, 7, 11], { s: 195, l: 150 }),
  { elapsed: '青緑の光が残った岩壁', current: '発光生物の群れ', remaining: '岩の輪郭だけの暗がり' }),

D('canopy-aperture', 'Canopy Aperture', 'fog',
  { substrate: 'canopy', sweep: 'diagonal', layout: 'scatter', density: 96, soft: 0.12, headSize: 0.3, scale: 1.25, sway: 1.4 },
  P(88, 34, { a: -46, k: -64, mid: 42 }),
  { type: 'join', affordance: '葉の影と光の葉が離れて浮かぶ', feedback: '重なるほど葉脈が見えてくる' },
  'leafVein',
  S('wood', [-7, 12], [-7, 12, 16], { s: 160, l: 140 }),
  { elapsed: '暖色になり輪郭の光る葉', current: '葉の隙間を移動する日差し', remaining: '冷たい影' }),

D('moonlit-wetlands', 'Moonlit Wetlands', 'trail',
  { scenery: 'reed', mark: 'ripple', agent: 'dot', knots: 6, marks: 44, field: 46, headSize: 0.15 },
  P(210, 24, { a: 10, k: 24, mid: 46 }),
  { type: 'hold', affordance: '三日月状の反射が水面に浮かぶ', feedback: '波紋が小さくなり、中央へ収束する' },
  'crescentRipple',
  S('water', [-14, -2], [-2, 9], { s: 175, l: 150 }),
  { elapsed: '銀色の揺れが残る水路', current: '最も明るい月光の反射', remaining: '暗い水面' }),

D('aurora-valley', 'Aurora Valley', 'strand',
  { mode: 'align', strands: 5, weight: 16, headSize: 0.26 },
  P(268, 40, { a: 82, k: 110, mid: 44 }),
  { type: 'join', affordance: '三本のオーロラの端と中央の光点', feedback: '重なった部分が柔らかい結び目へ変形する' },
  'ribbonKnot',
  S('air', [-12, -5], [0, 7, 0], { s: 210, l: 170 }),
  { elapsed: '淡い色層と星の輪郭', current: '最も明るい折り目', remaining: '濃紺の空' }),

// ══ 11–20 ════════════════════════════════════════════════════
D('shoji-light', 'Shoji Light Room', 'caustic',
  { material: 'paper', lightShape: 'pane', flecks: 120, headSize: 0.26 },
  P(44, 22, { a: -10, k: 8, mid: 50 }),
  { type: 'drag', affordance: '障子状の光片と畳の正方形の影', feedback: '桟の線が正確に重なっていく' },
  'squareLattice',
  S('wood', [-9, -2], [-2, -2], { s: 165, l: 230 }),
  { elapsed: '畳目と木目の鮮明な床', current: '長方形の光', remaining: '涼しい影' }),

D('stained-glass-hall', 'Stained Glass Hall', 'caustic',
  { material: 'stone', lightShape: 'prism', flecks: 130, seams: 3, headSize: 0.3 },
  P(258, 36, { a: 96, k: 150, mid: 42 }),
  { type: 'join', affordance: '二枚の小さな色ガラス片', feedback: '重なった部分の色が混ざり幾何学模様になる' },
  'rosette',
  S('glass', [0, 7], [-5, 7, 2], { s: 150, l: 145 }),
  { elapsed: '淡い残光の残る石床', current: '最も鮮やかな色ガラスの光', remaining: '無彩色の石' }),

D('museum-after-hours', 'Museum After Hours', 'caustic',
  { material: 'stone', lightShape: 'spot', flecks: 90, headSize: 0.3 },
  P(28, 18, { a: 6, k: 20, mid: 44 }),
  { type: 'hold', affordance: '最後に照らされた作品の上のスポット', feedback: '光が小さくなり、作品の下へ収束する' },
  'plate',
  S('resonant', [-8, -1], [-1, 3], { s: 200, l: 175 }),
  { elapsed: '素材と色が淡く残る作品', current: 'スポットライト', remaining: '輪郭だけの作品' }),

D('observatory-dome', 'Observatory Dome', 'radial',
  { wedges: 14, radius: 0.52, cy: 0.5 },
  P(232, 34, { a: 30, k: 60, mid: 40 }),
  { type: 'drag', affordance: '最後の星と望遠鏡のレンズ中央', feedback: 'レンズ内に二重の光輪が形成される' },
  'starRing',
  S('celestial', [16, 4], [16, 19], { s: 185, l: 165 }),
  { elapsed: '淡い接続線の残る星', current: 'スリット内の星空', remaining: 'ドームに隠れた空' }),

D('condensation-nook', 'Condensation Nook', 'fog',
  { substrate: 'panes', sweep: 'radial', layout: 'grid', density: 40, soft: 0.16, headSize: 0.3, scale: 1.0 },
  P(198, 20, { a: 18, k: 36, mid: 52 }),
  { type: 'trace', affordance: 'ガラスに短い曲線の曇りがのこる', feedback: '指の軌跡に沿ってガラスが透明になる' },
  'dropRing',
  S('glass', [4, 11], [11, 4, 11], { s: 170, l: 150 }),
  { elapsed: '街と木の見える透明なガラス', current: '晴れていく境界', remaining: '白く曇ったガラス' }),

D('ceramic-reflection', 'Ceramic Reflection', 'caustic',
  { material: 'ceramic', lightShape: 'bar', flecks: 160, headSize: 0.24 },
  P(20, 24, { a: 30, k: 50, mid: 50 }),
  { type: 'drag', affordance: '細い反射光と器の縁の小さなくぼみ', feedback: '器表面の光沢が反射位置へ集まる' },
  'fleck',
  S('ceramic', [-12, -5], [-5, -1], { s: 155, l: 135 }),
  { elapsed: '釉薬の粒子と焼きむらの見える面', current: '細い反射', remaining: 'マットな陶肌' }),

D('sleeper-train', 'Sleeper Train Window', 'depth',
  { motif: 'window', layers: 11, scale: 1.0 },
  P(222, 26, { a: 120, k: 38, mid: 40 }),
  { type: 'fold', affordance: '窓辺のカーテンタブ', feedback: '外の光が細くなり、車内の反射が強くなる' },
  'plate',
  S('wood', [-17, -10], [-10, -10, -5], { s: 145, l: 120 }),
  { elapsed: 'ガラス端に残る残像', current: '窓正面の風景', remaining: '遠くの暗闇' }),

D('rooftop-wind-map', 'Rooftop Wind Map', 'front',
  { item: 'panel', layout: 'grid', density: 28, sweep: 'columns', turn: 0.9, soft: 0.12, period: 7 },
  P(196, 18, { a: 40, k: 26, mid: 48 }),
  { type: 'fold', affordance: '一枚の布の端と中央の折り目', feedback: '布の揺れが徐々に落ち着く' },
  'crease',
  S('fabric', [-5, 2], [-5, -5, 2], { s: 150, l: 130 }),
  { elapsed: '弱い揺れの残る布', current: '最も大きく揺れる布', remaining: '静止した布' }),

D('greenhouse-mist', 'Greenhouse Mist Corridor', 'fog',
  { substrate: 'reeds', sweep: 'columns', layout: 'rows', density: 78, soft: 0.1, headSize: 0.3, scale: 1.2, sway: 1.1 },
  P(140, 30, { a: 38, k: 58, mid: 44 }),
  { type: 'drag', affordance: '大きな水滴と葉の先端', feedback: '水滴の通過に合わせて葉脈が光る' },
  'dropGlow',
  S('water', [0, 12], [12, 16], { s: 165, l: 140 }),
  { elapsed: '水滴と反射のついた葉', current: '薄い霧の中心', remaining: '乾いた葉の表面' }),

D('projection-dust', 'Projection Dust Theatre', 'swarm',
  { count: 130, spread: 0.16, settle: 'dot', knots: 5 },
  P(40, 16, { a: 8, k: 24, mid: 46 }),
  { type: 'trace', affordance: '投影光の先端がたどる短い軌道', feedback: '埃が光の中心へ集まる' },
  'dustRing',
  S('air', [-14, 7], [-14, -14, 7], { s: 160, l: 150 }),
  { elapsed: '空気中の埃と布の質感', current: '光の中心', remaining: '暗闇' }),

// ══ 21–30 ════════════════════════════════════════════════════
D('canal-lock', 'Canal Lock Passage', 'trail',
  { scenery: 'stone', mark: 'wake', agent: 'boat', knots: 7, marks: 40, field: 30, headSize: 0.14 },
  P(186, 26, { a: 26, k: 44, mid: 44 }),
  { type: 'drag', affordance: '小船と最後の静かな水面の中央', feedback: '水位が安定し、周囲の航跡が閉じていく' },
  'contourTriple',
  S('wood', [-14, -7], [-14, 5, 5], { s: 175, l: 150 }),
  { elapsed: '開いた水門と航跡', current: '小船と水位の変化', remaining: '閉じたままの水門' }),

D('alpine-switchbacks', 'Alpine Switchbacks', 'trail',
  { scenery: 'stone', mark: 'dash', agent: 'dot', knots: 9, marks: 50, field: 44, headSize: 0.16 },
  P(216, 20, { a: 30, k: 44, mid: 42 }),
  { type: 'trace', affordance: '最後の短い折り返し道', feedback: '霧がなぞった道から静かに後退する' },
  'halo',
  S('metal', [-5, -5], [-1, 2], { s: 200, l: 180 }),
  { elapsed: '暖色の反射と小さな光の残る道', current: '旅人の光', remaining: '霧の中の道' }),

D('kite-district', 'Kite District', 'trail',
  { scenery: 'bloom', mark: 'thread', agent: 'kite', knots: 8, marks: 56, field: 26, headSize: 0.14 },
  P(202, 30, { a: 44, k: 60, mid: 48 }),
  { type: 'hold', affordance: '凧糸の端', feedback: '糸の揺れが徐々に小さくなる' },
  'knot',
  S('string', [2, 9], [9, 14], { s: 160, l: 140 }),
  { elapsed: '糸の曲線が残る空', current: '風に乗る凧', remaining: '薄い風の流れだけの空' }),

D('migrating-flock', 'Migrating Flock', 'swarm',
  { count: 74, spread: 0.2, settle: 'dot', knots: 7 },
  P(224, 22, { a: 36, k: 52, mid: 46 }),
  { type: 'drag', affordance: '離れた先頭の鳥影と群れの中央', feedback: '他の鳥もゆっくり位置を調整する' },
  'arcTrail',
  S('air', [0, 7], [-5, 7], { s: 185, l: 160 }),
  { elapsed: '羽ばたきの軌跡が薄く残る空', current: '隊形を変える群れ', remaining: '手つかずの空' }),

D('submersible-biomes', 'Submersible Biomes', 'trail',
  { scenery: 'coral', mark: 'dot', agent: 'fish', knots: 6, marks: 44, field: 40, headSize: 0.2 },
  P(200, 40, { a: 20, k: 40, mid: 38 }),
  { type: 'drag', affordance: 'ライトと最後の海底走査点', feedback: '海底に幾何学的な走査線が広がる' },
  'hexScan',
  S('underwater', [-17, -17], [-17, -12, -17], { s: 230, l: 200 }),
  { elapsed: '生物と岩の輪郭', current: '潜水艇のライト', remaining: '暗い水域' }),

D('lantern-river', 'Lantern River', 'trail',
  { scenery: 'reed', mark: 'wake', agent: 'boat', knots: 7, marks: 46, field: 38, headSize: 0.18 },
  P(28, 34, { a: 16, k: 30, mid: 46 }),
  { type: 'drag', affordance: '灯りと三日月状の静かな渦', feedback: '航跡が灯りの周囲へ集まる' },
  'leafVein',
  S('metal', [4, 4], [4, 11], { s: 175, l: 155 }),
  { elapsed: '暖かい航跡の残る水面', current: '流れる一つの灯り', remaining: '暗い流れ' }),

D('seed-on-wind', 'Seed on Wind', 'trail',
  { scenery: 'bloom', mark: 'shimmer', agent: 'dot', knots: 9, marks: 52, field: 40, headSize: 0.13 },
  P(76, 26, { a: 40, k: 60, mid: 50 }),
  { type: 'drag', affordance: '種と空中の風の螺旋の中央', feedback: '種の回転と周囲の風線が落ち着く' },
  'spiral',
  S('air', [12, 19], [19, 12, 19], { s: 155, l: 135 }),
  { elapsed: '草の向きと反射の変わった場所', current: '風に運ばれる一粒の種', remaining: '風を受けていない草原' }),

D('tram-weather', 'Tram Weather Ribbon', 'depth',
  { motif: 'window', layers: 10, scale: 0.95 },
  P(178, 24, { a: 44, k: 66, mid: 46 }),
  { type: 'drag', affordance: '車内窓の暖色反射と最後尾の窓', feedback: '反射が車体上を滑らかに移動する' },
  'plate',
  S('digital', [0, 7], [0, 9, 4], { s: 150, l: 130 }),
  { elapsed: '鮮明になった建物', current: '車窓の天気', remaining: '霧の中の街' }),

D('moon-rover', 'Moon Rover Survey', 'trail',
  { scenery: 'stone', mark: 'track', agent: 'rover', knots: 8, marks: 60, field: 46, headSize: 0.18 },
  P(210, 12, { a: 40, k: 56, mid: 44 }),
  { type: 'trace', affordance: '最後の短い走査弧', feedback: '地面へ幾何学線が広がる' },
  'hexScan',
  S('digital', [-12, 7], [-12, -12, 9], { s: 145, l: 125 }),
  { elapsed: '車輪跡と測定済みの岩', current: '探査車のライト', remaining: '曖昧な地形' }),

D('firefly-maze', 'Firefly Hedge Maze', 'swarm',
  { count: 84, spread: 0.13, settle: 'glowdot', knots: 9 },
  P(104, 32, { a: 44, k: 58, mid: 36 }),
  { type: 'join', affordance: '離れた二群の発光体', feedback: '迷路内の残光が中央へ流れる' },
  'halo',
  S('glass', [9, 9], [9, 16, 12], { s: 190, l: 160 }),
  { elapsed: '葉の縁に光の残る通路', current: '移動する発光体', remaining: '暗い通路' }),

// ══ 31–40 ════════════════════════════════════════════════════
D('magnetic-silk', 'Magnetic Silk', 'front',
  { item: 'fiber', layout: 'grid', density: 150, sweep: 'radial', turn: 1.3, soft: 0.14, scale: 0.9 },
  P(258, 26, { a: 30, k: 60, mid: 46 }),
  { type: 'hold', affordance: '見えない磁力の中心', feedback: '周囲の繊維が少しずつ編み目へ変わる' },
  'weavePatch',
  S('metal', [-24, -12], [-24, -12, -12], { s: 165, l: 140, so: { noiseAmount: 0.3 } }),
  { elapsed: '新しい方向へ整列した繊維', current: '磁力の中心', remaining: 'ばらばらな向きの繊維' }),

D('ferrofluid-basin', 'Ferrofluid Basin', 'liquid',
  { style: 'ferro', bands: 5, blobs: 7, hueStep: 4 },
  P(246, 20, { a: 20, k: 50, mid: 34 }),
  { type: 'drag', affordance: '小さな磁性滴と器の中央', feedback: '突起群が滴の周囲へ集まる' },
  'rosette',
  S('metal', [-19, -12], [-19, -19, -7], { s: 150, l: 130 }),
  { elapsed: '低い波紋と金属反射', current: '磁力による突起群', remaining: '滑らかな液面' }),

D('marble-logic', 'Marble Logic', 'trail',
  { scenery: 'stone', mark: 'shimmer', agent: 'dot', knots: 10, marks: 48, field: 24, routeWidth: 3.4, headSize: 0.14 },
  P(188, 26, { a: 60, k: 120, mid: 52 }),
  { type: 'drag', affordance: '球体と最後の透明な受け皿', feedback: '管内の屈折光が球体へ集まる' },
  'prismHex',
  S('glass', [12, 19], [19, 24], { s: 150, l: 130 }),
  { elapsed: '色と透明度の変わった管', current: '転がる球体', remaining: '素通しの管' }),

D('balanced-mobile', 'Balanced Mobile', 'front',
  { item: 'pendulum', layout: 'scatter', density: 22, sweep: 'columns', soft: 0.16, period: 9, scale: 1.2 },
  P(34, 22, { a: 160, k: 30, mid: 48 }),
  { type: 'drag', affordance: '最後の小さな重りと空いている接続部', feedback: 'モビール全体がゆっくりバランスを取り直す' },
  'constellation',
  S('metal', [-5, 11], [-5, 11], { s: 240, l: 150 }),
  { elapsed: '新しい角度へ落ち着いた部品', current: '移動する重み', remaining: '手つかずのバランス' }),

D('moebius-sheen', 'Moebius Sheen', 'strand',
  { mode: 'braid', strands: 2, weight: 26, headSize: 0.22 },
  P(280, 26, { a: 70, k: 110, mid: 46 }),
  { type: 'trace', affordance: '帯の上の短い光の縫い目', feedback: '表裏に分かれていた反射が連続する' },
  'stitch',
  S('glass', [2, 9], [9, 2, 11], { s: 170, l: 145 }),
  { elapsed: '織り目と虹色光沢', current: '表裏を移動する反射', remaining: 'マットな帯' }),

D('kinetic-sand', 'Kinetic Sand Cartography', 'lines',
  { axis: 'h', density: 24, weight: 1.8 },
  P(36, 22, { a: 10, k: 24, mid: 50 }),
  { type: 'trace', affordance: '閉じていない最後の等高線', feedback: '線の両端が近づき、砂の影が整う' },
  'contourTriple',
  S('fabric', [-12, -5], [-12, -12, -1], { s: 145, l: 125 }),
  { elapsed: '地図と波紋の描かれた砂面', current: 'スタイラスの先', remaining: '平らな砂' }),

D('prism-caustics', 'Prism Caustics', 'caustic',
  { material: 'stone', lightShape: 'prism', flecks: 110, headSize: 0.28 },
  P(210, 22, { a: 110, k: 160, mid: 50 }),
  { type: 'drag', affordance: 'プリズムと複数の光線の焦点', feedback: '虹色の線が中央へ収束する' },
  'prismHex',
  S('glass', [7, 14], [7, 11, 14], { s: 160, l: 140 }),
  { elapsed: '薄い虹色の残光', current: '屈折光', remaining: '無彩色の床' }),

D('pendulum-choir', 'Pendulum Choir', 'front',
  { item: 'pendulum', layout: 'columns', density: 13, sweep: 'columns', soft: 0.2, scale: 1.4 },
  P(214, 18, { a: 24, k: 40, mid: 46 }),
  { type: 'hold', affordance: '中央の小さな支点', feedback: '振り子の位相差が徐々に小さくなる' },
  'plate',
  S('wood', [-10, -3], [-10, -6, -3], { s: 175, l: 145 }),
  { elapsed: '位相の揃った振り子', current: '一時的に揃う領域', remaining: 'ばらばらの位相' }),

D('soft-hinge-wall', 'Soft Hinge Wall', 'front',
  { item: 'panel', layout: 'grid', density: 24, sweep: 'columns', turn: 1.0, soft: 0.1 },
  P(18, 20, { a: 20, k: 34, mid: 48 }),
  { type: 'fold', affordance: '最後の一枚のパネル', feedback: '他のパネルの微振動が静まる' },
  'crease',
  S('fabric', [-7, -7], [-7, -14], { s: 160, l: 140 }),
  { elapsed: '裏面素材を見せて落ち着いたパネル', current: '傾きの波', remaining: '正面を向いたパネル' }),

D('wind-tunnel-fibers', 'Wind Tunnel Fibers', 'front',
  { item: 'fiber', layout: 'columns', density: 90, sweep: 'columns', turn: 1.6, soft: 0.08, scale: 1.1 },
  P(164, 20, { a: 40, k: 62, mid: 48 }),
  { type: 'hold', affordance: '最後に揺れている数本の繊維', feedback: '繊維が中央へ寄り、揺れが小さくなる' },
  'weavePatch',
  S('fabric', [-9, -2], [-9, -9, 3], { s: 150, l: 130 }),
  { elapsed: '弱い揺れの残る繊維', current: '風圧の帯', remaining: '静止した繊維' })
,

// ══ 41–50 ════════════════════════════════════════════════════
D('ant-archive', 'Ant Archive', 'trail',
  { scenery: 'stone', mark: 'dot', agent: 'dot', knots: 10, marks: 58, field: 48, headSize: 0.12 },
  P(24, 26, { a: 26, k: 44, mid: 40 }),
  { type: 'drag', affordance: '小さな結晶と壁のくぼみ', feedback: '周囲の砂粒が結晶の形に沿って整う' },
  'fleck',
  S('wood', [-14, -14], [-14, -9], { s: 190, l: 165 }),
  { elapsed: '鉱物と根と砂層の見える通路', current: '探索する一匹の蟻', remaining: '暗い通路' }),

D('hermit-crab', 'Hermit Crab Tidepools', 'trail',
  { scenery: 'stone', mark: 'ripple', agent: 'snail', knots: 8, marks: 46, field: 42, headSize: 0.13 },
  P(16, 22, { a: 172, k: 190, mid: 52 }),
  { type: 'drag', affordance: '真珠色の殻片とヤドカリの軌跡の末端', feedback: '濡れた反射が螺旋へ集まる' },
  'spiral',
  S('ceramic', [-2, -2], [-2, 5, 12], { s: 185, l: 150 }),
  { elapsed: '水の反射と小さな足跡', current: '移動するヤドカリ', remaining: '乾いた岩' }),

D('koi-current', 'Koi Current Map', 'trail',
  { scenery: 'reed', mark: 'thread', agent: 'fish', knots: 9, marks: 60, field: 30, headSize: 0.16 },
  P(348, 30, { a: 200, k: 186, mid: 44 }),
  { type: 'trace', affordance: '最後の短い水流線', feedback: '複数の流線が柔らかく組み合わさる' },
  'knot',
  S('water', [-14, 0], [0, 0, -14], { s: 180, l: 150 }),
  { elapsed: '絹のような水流線', current: '泳ぐ一匹の鯉', remaining: '流れの見えない水面' }),

D('gecko-mosaic', 'Gecko Mosaic', 'front',
  { item: 'tile', layout: 'grid', density: 60, sweep: 'diagonal', soft: 0.1 },
  P(198, 26, { a: 170, k: 150, mid: 48 }),
  { type: 'hold', affordance: '最後に暖かくなったタイル', feedback: 'タイル表面の熱模様が中央へまとまる' },
  'heatMark',
  S('ceramic', [-5, -5], [-5, 0], { s: 165, l: 140 }),
  { elapsed: '体温の残る暖かいタイル', current: '移動するヤモリ', remaining: '冷たいタイル' }),

D('moth-window', 'Moth and Window Light', 'trail',
  { scenery: 'star', mark: 'shimmer', agent: 'moth', knots: 11, marks: 50, field: 56, headSize: 0.15 },
  P(48, 16, { a: 170, k: 26, mid: 44 }),
  { type: 'drag', affordance: '蛾と月光の中の薄い円', feedback: '埃の軌跡が円の周囲へ集まる' },
  'halo',
  S('air', [16, 23], [23, 16, 23], { s: 145, l: 135 }),
  { elapsed: '埃が光る短い軌跡', current: '蛾と月光', remaining: '暗い部屋' }),

D('jelly-colony', 'Jelly Colony', 'swarm',
  { count: 54, spread: 0.24, settle: 'glowdot', knots: 5 },
  P(206, 38, { a: 30, k: 56, mid: 40 }),
  { type: 'join', affordance: '離れた二つのクラゲの光', feedback: '他のクラゲの収縮周期が徐々に揃う' },
  'halo',
  S('underwater', [-19, -12], [-12, -12], { s: 240, l: 210 }),
  { elapsed: '触手の軌跡と光粒', current: '最も密集した群れ', remaining: '暗い水域' }),

D('bee-pollination', 'Bee Pollination Weave', 'trail',
  { scenery: 'bloom', mark: 'thread', agent: 'dot', knots: 11, marks: 62, field: 34, headSize: 0.12 },
  P(52, 40, { a: 26, k: 40, mid: 52 }),
  { type: 'trace', affordance: '最後の花粉の糸', feedback: '既存の糸がわずかに張り直される' },
  'weavePatch',
  S('resonant', [-17, -5], [-17, 7, 7], { s: 165, l: 140 }),
  { elapsed: '花をつなぐ花粉の糸', current: '飛ぶ蜂', remaining: '接続線のない花' }),

D('maintenance-robot', 'Maintenance Robot Circuit', 'trail',
  { scenery: 'stone', mark: 'dash', agent: 'rover', knots: 12, marks: 70, field: 40, routeWidth: 2.2, headSize: 0.15 },
  P(168, 34, { a: 44, k: 66, mid: 42 }),
  { type: 'drag', affordance: 'ロボットと淡く点灯したドック', feedback: '修復済み回路の光がロボットへ追従する' },
  'loopCircuit',
  S('digital', [-12, 0], [0, 0, -12], { s: 150, l: 130 }),
  { elapsed: '細い光の流れる回路', current: '整備ロボット', remaining: '暗い回路' }),

D('seahorse-kelp', 'Seahorse Kelp', 'trail',
  { scenery: 'reed', mark: 'shimmer', agent: 'fish', knots: 7, marks: 48, field: 52, headSize: 0.16 },
  P(158, 32, { a: 40, k: 58, mid: 42 }),
  { type: 'drag', affordance: 'タツノオトシゴと海藻の小さな巻き', feedback: '海流線が海藻の周囲へ巻き付く' },
  'spiral',
  S('underwater', [-5, 2], [-5, 2], { s: 215, l: 185 }),
  { elapsed: '異なる揺れと反射の海藻', current: '海流に運ばれるタツノオトシゴ', remaining: '一様に揺れる海藻' }),

D('snail-leaf-city', 'Snail Leaf City', 'trail',
  { scenery: 'bloom', mark: 'shimmer', agent: 'snail', knots: 9, marks: 54, field: 36, headSize: 0.12 },
  P(112, 28, { a: 150, k: 200, mid: 46 }),
  { type: 'drag', affordance: 'カタツムリと葉の上の露の輪', feedback: '虹色の軌跡が露の周囲へ集まる' },
  'spiral',
  S('glass', [0, 0], [0, 7], { s: 175, l: 155 }),
  { elapsed: '虹色の薄い軌跡', current: '進むカタツムリ', remaining: '乾いた葉面' }),

// ══ 51–60 ════════════════════════════════════════════════════
D('braided-current', 'Braided Current', 'strand',
  { mode: 'braid', strands: 3, weight: 13, headSize: 0.2 },
  P(192, 32, { a: 44, k: 74, mid: 46 }),
  { type: 'join', affordance: '三本の終端と中央の小さな輪', feedback: '終端が互いの上下を入れ替えながらまとまる' },
  'knot',
  S('resonant', [-5, 2, 9], [-5, 2, 9], { s: 130, l: 110 }),
  { elapsed: '密度のある編み模様', current: '編み込みの境界', remaining: '分離した三本の流れ' }),

D('voronoi-pressure', 'Voronoi Pressure', 'front',
  { item: 'tile', layout: 'scatter', density: 44, sweep: 'radial', soft: 0.16, scale: 1.6 },
  P(272, 20, { a: 50, k: 80, mid: 44 }),
  { type: 'hold', affordance: '見えない圧力点', feedback: '周囲のセルが対称ではない安定形へ整う' },
  'crystal6',
  S('digital', [-17, -17], [-17, -10], { s: 170, l: 150 }),
  { elapsed: '新しい形状と質感へ落ち着いたセル', current: '圧力点', remaining: '押されていないセル' }),

D('contour-tide', 'Contour Tide', 'lines',
  { axis: 'v', density: 34, weight: 1.4 },
  P(200, 28, { a: 28, k: 48, mid: 46 }),
  { type: 'trace', affordance: '最後の開いた等高線', feedback: '周囲の線が閉じた形へ引き寄せられる' },
  'contourTriple',
  S('resonant', [-24, -17], [-24, -12, -5], { s: 175, l: 150 }),
  { elapsed: '別の地形へ変化した等高線', current: '密度の高い波', remaining: '元の地形' }),

D('phase-cube-field', 'Phase Cube Field', 'front',
  { item: 'cube', layout: 'grid', density: 48, sweep: 'diagonal', soft: 0.12 },
  P(28, 16, { a: 190, k: 30, mid: 46 }),
  { type: 'fold', affordance: '最後の立方体の面', feedback: '周囲の立方体も数度だけ角度を調整する' },
  'weavePatch',
  S('wood', [-7, -7], [-7, -3, 0], { s: 165, l: 140 }),
  { elapsed: '異なる素材面を見せる立方体', current: '傾きの波', remaining: '同じ面の立方体' }),

D('interference-loom', 'Interference Loom', 'lines',
  { axis: 'v', density: 46, weight: 1.0 },
  P(240, 30, { a: 60, k: 96, mid: 48 }),
  { type: 'drag', affordance: '小さな位相点と二組の線が安定する位置', feedback: 'うなりのような視覚の揺れが徐々に減る' },
  'rosette',
  S('resonant', [0, 1], [0, 1, 7], { s: 165, l: 140, so: { detune: 12 } }),
  { elapsed: '位相の変わった別模様', current: '最も美しい干渉領域', remaining: '元の位相の曲線群' }),

D('elastic-mesh', 'Elastic Mesh Traveler', 'front',
  { item: 'node', layout: 'grid', density: 130, sweep: 'radial', soft: 0.15, scale: 1.2 },
  P(150, 24, { a: 44, k: 66, mid: 46 }),
  { type: 'drag', affordance: '光点と網面の小さなくぼみ', feedback: '網の張力が均一になっていく' },
  'halo',
  S('string', [-5, 2], [-5, -1], { s: 170, l: 145 }),
  { elapsed: '弱い振動と形状記憶', current: '網を引く光点', remaining: '張ったままの網' }),

D('chromatic-echo', 'Chromatic Echo', 'swarm',
  { count: 40, spread: 0.26, settle: 'dot', knots: 6 },
  P(310, 34, { a: 40, k: 70, mid: 48 }),
  { type: 'hold', affordance: '最新の形状', feedback: '複数の残像が現在位置へ少しずつ集まる' },
  'halo',
  S('glass', [4, 16], [4, 16, 4], { s: 180, l: 155, lo: { reverbAmount: 0.5 } }),
  { elapsed: '色と透明度の異なる残像', current: '有機形状の現在位置', remaining: '残像のない空間' }),

D('tessellation-frontier', 'Tessellation Frontier', 'front',
  { item: 'tile', layout: 'grid', density: 80, sweep: 'columns', soft: 0.06 },
  P(60, 24, { a: 180, k: 200, mid: 50 }),
  { type: 'drag', affordance: '両方の特徴を持つ中間タイルと境界', feedback: '周囲の形が中間タイルへ合わせて変形する' },
  'weavePatch',
  S('ceramic', [-5, 4], [-5, 4, -5], { s: 160, l: 140 }),
  { elapsed: '新しい敷き詰め模様', current: '連続変形する境界', remaining: '元の敷き詰め模様' }),

D('ink-solvent', 'Ink Solvent Path', 'liquid',
  { style: 'ink', bands: 12, hueStep: 3 },
  P(258, 26, { a: 20, k: 50, mid: 36 }),
  { type: 'trace', affordance: '最後の短い透明な経路', feedback: 'インクの境界が自然ににじみながら後退する' },
  'rosette',
  S('water', [-9, 3], [3, 3, -9], { s: 160, l: 140, so: { noiseAmount: 0.4 } }),
  { elapsed: '紙繊維と淡い色の見える面', current: '透明な液滴', remaining: '濃いインク' }),

D('flock-metamorphosis', 'Flock Metamorphosis', 'swarm',
  { count: 150, spread: 0.22, settle: 'dot', knots: 8 },
  P(230, 26, { a: 50, k: 76, mid: 46 }),
  { type: 'hold', affordance: '群れ中央の光核', feedback: '粒子の速度が下がり、中心の周囲へ集まる' },
  'halo',
  S('air', [-5, 7], [-5, 2, 7], { s: 150, l: 130 }),
  { elapsed: '穏やかな流れへ移った粒子', current: '最も密度の高い領域', remaining: '未変形の群れ' }),

// ══ 61–70 ════════════════════════════════════════════════════
D('loom-shuttle', 'Loom Shuttle', 'trail',
  { scenery: 'reed', mark: 'stitch', agent: 'shuttle', knots: 12, marks: 72, field: 60, routeWidth: 1.2, headSize: 0.12 },
  P(12, 28, { a: 36, k: 58, mid: 47 }),
  { type: 'drag', affordance: '杼と最後の縦糸の隙間', feedback: '糸の張力が整い、最後の横糸が通る' },
  'knot',
  S('wood', [-9, -2], [-9, -9, -2], { s: 155, l: 130 }),
  { elapsed: '複数色の織物模様', current: '移動する杼', remaining: '縦糸だけの領域' }),

D('suminagashi', 'Suminagashi Channel', 'liquid',
  { style: 'marble', bands: 10, hueStep: 8 },
  P(216, 22, { a: 30, k: 60, mid: 44 }),
  { type: 'trace', affordance: '最後の短い櫛の軌跡', feedback: '周囲の色が細い層へ分かれる' },
  'spiral',
  S('water', [-7, 5], [-7, 5, 9], { s: 170, l: 145 }),
  { elapsed: '複雑なマーブル模様', current: '細い櫛状の波', remaining: '大きな色面' }),

D('kintsugi-light', 'Kintsugi Light', 'caustic',
  { material: 'ceramic', lightShape: 'spot', flecks: 120, seams: 5, headSize: 0.26 },
  P(30, 26, { a: 14, k: 26, mid: 50 }),
  { type: 'trace', affordance: '最後の短いひび', feedback: '複数の光が接続点へ集まる' },
  'goldSeam',
  S('ceramic', [-12, -1], [-1, -1, -12], { s: 170, l: 145 }),
  { elapsed: '淡い金属光沢の残るひび', current: '分岐しながら進む暖かな光', remaining: '暗いひび' }),

D('woodgrain-oil', 'Woodgrain Oil', 'caustic',
  { material: 'wood', lightShape: 'slit', flecks: 44, headSize: 0.28 },
  P(26, 30, { a: 8, k: 20, mid: 42 }),
  { type: 'drag', affordance: '小さな布片と最後の乾いた部分', feedback: '布の通過位置から木目が深く見える' },
  'moonArc',
  S('wood', [-17, -17], [-17, -12], { s: 185, l: 160 }),
  { elapsed: '木目と色と反射の深まった面', current: 'オイルの境界', remaining: '乾いた木材' }),

D('enamel-heat', 'Enamel Heat', 'front',
  { item: 'tile', layout: 'grid', density: 36, sweep: 'radial', soft: 0.14, scale: 1.1 },
  P(340, 30, { a: 30, k: 60, mid: 46 }),
  { type: 'hold', affordance: '最後の熱点', feedback: '熱の揺らぎが小さな形へ収束する' },
  'heatMark',
  S('ceramic', [7, 7], [7, 12], { s: 160, l: 140 }),
  { elapsed: '虹色の焼き色と反射', current: '熱の中心', remaining: 'マットなエナメル板' }),

D('paper-relief', 'Paper Relief', 'caustic',
  { material: 'paper', lightShape: 'bar', flecks: 120, headSize: 0.26 },
  P(40, 14, { a: 14, k: 30, mid: 52, bg: 8 }),
  { type: 'drag', affordance: '小さな光片と最後のくぼみ', feedback: '周囲の紙影が一つの形へ整う' },
  'crease',
  S('fabric', [-14, -14], [-14, -7, -14], { s: 165, l: 145 }),
  { elapsed: '層と切り口の鮮明な紙', current: '斜めの光', remaining: '平坦に見える層' }),

D('embroidery-path', 'Embroidery Path', 'trail',
  { scenery: 'bloom', mark: 'stitch', agent: 'shuttle', knots: 10, marks: 64, field: 28, routeWidth: 1.0, headSize: 0.1 },
  P(348, 24, { a: 30, k: 56, mid: 50 }),
  { type: 'drag', affordance: '糸端と最後の穴', feedback: '糸のたるみが徐々に減る' },
  'stitch',
  S('string', [0, 0], [0, 4], { s: 190, l: 160 }),
  { elapsed: '刺繍糸の残る下絵', current: '針と糸', remaining: '薄い下絵だけ' }),

D('glassbreath', 'Glassbreath Chamber', 'liquid',
  { style: 'oil', bands: 7, hueStep: 16 },
  P(186, 30, { a: 40, k: 80, mid: 50 }),
  { type: 'drag', affordance: '色の細い帯と内部の気泡', feedback: '帯が気泡の周囲へ巻き付く' },
  'bubbleSeal',
  S('glass', [-2, -2], [-2, 10], { s: 200, l: 175, so: { noiseAmount: 0.3 } }),
  { elapsed: '層と気泡と色の筋', current: '移動する色の帯', remaining: '透明に近いガラス' }),

D('cyanotype', 'Cyanotype Exposure', 'caustic',
  { material: 'paper', lightShape: 'slit', flecks: 100, headSize: 0.3 },
  P(214, 40, { a: 10, k: 20, mid: 46 }),
  { type: 'drag', affordance: '小さな遮光片と最後の明るい領域', feedback: '青色が静かに定着する' },
  'halo',
  S('air', [4, 16], [4, 4, 16], { s: 150, l: 130 }),
  { elapsed: '青が深まり影の輪郭が出た紙', current: '露光の境界', remaining: '淡い青白色の紙' }),

D('soap-film', 'Soap Film Cathedral', 'radial',
  { wedges: 16, radius: 0.5, cy: 0.5 },
  P(190, 26, { a: 80, k: 150, mid: 52 }),
  { type: 'join', affordance: '離れている膜の二つの縁', feedback: '色帯が重なり部分へ収束する' },
  'prismHex',
  S('resonant', [-1, -1], [-1, 6], { s: 210, l: 180 }),
  { elapsed: '別の虹色層へ落ち着いた膜', current: '鮮やかな干渉色の帯', remaining: '銀色の膜' })
,

// ══ 71–80 ════════════════════════════════════════════════════
D('memory-palace', 'Memory Palace Corridor', 'depth',
  { motif: 'corridor', layers: 12, scale: 1.0 },
  P(34, 20, { a: 12, k: 26, mid: 44 }),
  { type: 'drag', affordance: '扉の小さな真鍮反射と取っ手', feedback: '扉の隙間の光が細くなる' },
  'plate',
  S('resonant', [-10, -3], [-10, -3, -10], { s: 195, l: 165 }),
  { elapsed: '鏡と反射に小さく残る部屋', current: '進む視点', remaining: '奥の霧' }),

D('glyph-river', 'Glyph River', 'lines',
  { axis: 'v', density: 28, weight: 2.2 },
  P(206, 20, { a: 26, k: 44, mid: 48 }),
  { type: 'trace', affordance: '最後の短い筆画', feedback: '周囲の筆画が結び目状に整う' },
  'knot',
  S('wood', [-5, 2], [2, 2, -5], { s: 160, l: 140, so: { noiseAmount: 0.4 } }),
  { elapsed: '帯状に並んだ筆画', current: '整列させる水流', remaining: 'ばらばらに漂う筆画' }),

D('semantic-constellation', 'Semantic Constellation', 'front',
  { item: 'node', layout: 'scatter', density: 56, sweep: 'diagonal', soft: 0.14, scale: 1.7 },
  P(248, 30, { a: 44, k: 74, mid: 44 }),
  { type: 'join', affordance: '最後に離れている二つのノード', feedback: '周囲の接続線が張力を調整する' },
  'constellation',
  S('celestial', [-5, 7, 14], [-5, 7, 14], { s: 190, l: 135 }),
  { elapsed: '接続線と色関係の残る領域', current: '移動する光', remaining: '未接続のノード' }),

D('breath-sculpture', 'Breath Sculpture', 'front',
  { item: 'lantern', layout: 'ring', density: 40, sweep: 'radial', soft: 0.16, scale: 1.4, period: 11 },
  P(178, 22, { a: 30, k: 52, mid: 46 }),
  { type: 'hold', affordance: '最後に膨らんだ空洞', feedback: '彫刻全体がゆっくり息を吐く' },
  'halo',
  S('air', [-12, -5], [-5, 2], { s: 200, l: 170 }),
  { elapsed: '弱く呼吸する膜', current: '空気が満ちている場所', remaining: 'しぼんだままの空洞' }),

D('translation-weave', 'Translation Weave', 'strand',
  { mode: 'weave', strands: 6, weight: 9, headSize: 0.22 },
  P(304, 26, { a: 60, k: 96, mid: 46 }),
  { type: 'join', affordance: '両側の細い模様の端', feedback: '二つの模様が互いの形へ少しずつ変化する' },
  'stitch',
  S('resonant', [-7, 5], [-7, 5], { s: 180, l: 120 }),
  { elapsed: '両方の性質を持つ模様', current: '編み込みの境界', remaining: '直線と曲線の別れた領域' }),

D('index-card-current', 'Index Card Current', 'front',
  { item: 'card', layout: 'rows', density: 40, sweep: 'columns', soft: 0.07, scale: 1.3 },
  P(42, 16, { a: 180, k: 200, mid: 52 }),
  { type: 'hold', affordance: '最後に反転したカード', feedback: 'カードの揺れが止まり、周囲のカードが避ける' },
  'weavePatch',
  S('fabric', [-9, -2], [-9, -9, -2], { s: 150, l: 130 }),
  { elapsed: '抽象図形の見えるカード', current: '反転しているカード', remaining: '裏向きのカード' }),

D('idea-metro', 'Idea Metro', 'trail',
  { scenery: 'star', mark: 'dash', agent: 'dot', knots: 11, marks: 66, field: 44, routeWidth: 2.6, headSize: 0.14 },
  P(268, 34, { a: 90, k: 150, mid: 48 }),
  { type: 'trace', affordance: '最後の短い分岐線', feedback: '複数路線の光が接続点へ集まる' },
  'loopCircuit',
  S('digital', [-5, 2], [-5, 4, -1], { s: 145, l: 125 }),
  { elapsed: '色と太さの変わった分岐', current: '分岐しながら進む光', remaining: '暗い線' }),

D('sentence-loom', 'Sentence Loom', 'strand',
  { mode: 'weave', strands: 7, weight: 11, headSize: 0.2 },
  P(14, 22, { a: 30, k: 50, mid: 48 }),
  { type: 'drag', affordance: '最後のリボン端と既存の編み目', feedback: '上下関係が滑らかに入れ替わる' },
  'knot',
  S('string', [-12, -5], [-12, -5, -1], { s: 175, l: 145 }),
  { elapsed: '一つの面へ編まれたリボン', current: '交差している場所', remaining: '分離したリボン' }),

D('phonetic-landscape', 'Phonetic Landscape', 'swarm',
  { count: 120, spread: 0.19, settle: 'dot', knots: 7 },
  P(16, 20, { a: 24, k: 46, mid: 46 }),
  { type: 'drag', affordance: '最後の粒子流と空洞中央の共鳴点', feedback: '粒子が楕円状に整列する' },
  'halo',
  S('resonant', [-10, -3], [-10, -3, -10], { s: 185, l: 160 }),
  { elapsed: '共鳴色と弱い振動の残る空洞', current: '移動する粒子群', remaining: '静かな空洞' }),

D('knowledge-archipelago', 'Knowledge Archipelago', 'depth',
  { motif: 'islands', layers: 12, scale: 1.1 },
  P(196, 28, { a: 30, k: 54, mid: 44 }),
  { type: 'drag', affordance: '船と最後の静かな入り江', feedback: '航路の光が入り江へ収束する' },
  'crescentRipple',
  S('metal', [-1, -1], [-1, 6, -12], { s: 200, l: 165 }),
  { elapsed: '海岸線の鮮明な島と航路', current: '光の船', remaining: '霧に隠れた島' }),

// ══ 81–90 ════════════════════════════════════════════════════
D('handpan-ripples', 'Handpan Ripples', 'front',
  { item: 'bowl', layout: 'ring', density: 26, sweep: 'radial', soft: 0.16, scale: 1.3 },
  P(200, 18, { a: 24, k: 46, mid: 46 }),
  { type: 'hold', affordance: '最後の振動の中心', feedback: '周囲の波が中央へ整う' },
  'dropRing',
  S('resonant', [-17, -10], [-17, -10], { s: 215, l: 170 }),
  { elapsed: '弱い干渉波の残る音面', current: '伝わる振動', remaining: '暗く静かな音面' }),

D('harp-wind', 'Harp Wind', 'front',
  { item: 'fiber', layout: 'columns', density: 34, sweep: 'columns', turn: 0.9, soft: 0.07, scale: 2.2 },
  P(46, 26, { a: 14, k: 30, mid: 50 }),
  { type: 'trace', affordance: '最後の風線と一本の弦', feedback: '他の弦の振動が静かに収まる' },
  'reflectLine',
  S('string', [-5, 7], [-5, 7], { s: 200, l: 170 }),
  { elapsed: '淡い光の残響の残る弦', current: '風の帯', remaining: '静止した弦' }),

D('music-box-terrain', 'Music Box Terrain', 'front',
  { item: 'key', layout: 'columns', density: 26, sweep: 'columns', soft: 0.06, scale: 1.2 },
  P(196, 16, { a: 40, k: 60, mid: 48 }),
  { type: 'drag', affordance: 'シリンダーの最後の小突起と金属片', feedback: '金属片がわずかにしなり、波が中央へ集まる' },
  'halo',
  S('ceramic', [16, 16], [16, 21], { s: 165, l: 140 }),
  { elapsed: '空気中へ広がった細い波', current: '接触している領域', remaining: '触れられていない金属片' }),

D('harmonic-lattice', 'Harmonic Lattice', 'front',
  { item: 'node', layout: 'grid', density: 110, sweep: 'diagonal', soft: 0.12, scale: 1.5 },
  P(258, 28, { a: 50, k: 80, mid: 46 }),
  { type: 'join', affordance: '最後に離れた二つのノード', feedback: '周囲のノードの明滅周期が揃う' },
  'hexScan',
  S('resonant', [-17, -5, 7], [-17, -5, 7], { s: 175, l: 120 }),
  { elapsed: '弱い周期で呼吸するノード', current: '調和領域', remaining: '静止したノード' }),

D('bell-chamber', 'Bell Chamber', 'front',
  { item: 'bell', layout: 'scatter', density: 26, sweep: 'radial', soft: 0.15, scale: 1.5, period: 6 },
  P(38, 22, { a: 170, k: 26, mid: 48 }),
  { type: 'hold', affordance: '中央の鐘の共鳴輪', feedback: '他の鐘の揺れが徐々に小さくなる' },
  'halo',
  S('metal', [-5, -5], [-5, 2], { s: 230, l: 190 }),
  { elapsed: 'ゆっくり揺れ続ける鐘', current: '半透明の共鳴', remaining: '静止した鐘' }),

D('ribbon-conductor', 'Ribbon Conductor', 'strand',
  { mode: 'align', strands: 6, weight: 12, headSize: 0.24 },
  P(330, 26, { a: 40, k: 70, mid: 48 }),
  { type: 'fold', affordance: '二本のリボン端と中央', feedback: '他のリボンが少しずつ同じ方向へ傾く' },
  'ribbonKnot',
  S('fabric', [-7, 0], [-7, 0, 5], { s: 165, l: 140 }),
  { elapsed: '緩やかな波へ落ち着いたリボン', current: '指揮領域', remaining: '未変形のリボン' }),

D('polyrhythm-orbs', 'Polyrhythm Orbs', 'front',
  { item: 'orb', layout: 'ring', density: 34, sweep: 'wedge', soft: 0.14, scale: 1.4 },
  P(140, 24, { a: 50, k: 90, mid: 46 }),
  { type: 'drag', affordance: '一つの球体と空いた位置', feedback: '他の球体の周期が少しずつ同期する' },
  'halo',
  S('wood', [-12, -3], [-12, -3, -8], { s: 230, l: 190 }),
  { elapsed: '別の周期関係へ移った球体', current: '美しく揃った配置', remaining: 'ばらばらな周期' }),

D('piano-lightfield', 'Piano Lightfield', 'front',
  { item: 'key', layout: 'columns', density: 22, sweep: 'columns', soft: 0.05, scale: 1.5 },
  P(210, 14, { a: 40, k: 24, mid: 50 }),
  { type: 'trace', affordance: '数枚の鍵盤の上を通る最後の光', feedback: '鍵盤が順番に静かに沈む' },
  'plate',
  S('resonant', [-8, -8], [-8, -1], { s: 220, l: 175 }),
  { elapsed: '長い影の残る鍵盤', current: '柔らかな光', remaining: '沈んでいない鍵盤' }),

D('resonant-bowls', 'Resonant Bowls', 'front',
  { item: 'bowl', layout: 'grid', density: 20, sweep: 'diagonal', soft: 0.16, scale: 1.5 },
  P(166, 20, { a: 30, k: 56, mid: 48 }),
  { type: 'join', affordance: '二つの器の波紋の中心', feedback: '干渉波が花形へ変化する' },
  'rosette',
  S('resonant', [-22, -22], [-22, -15], { s: 235, l: 200 }),
  { elapsed: '波紋の残る器', current: '移動する共鳴', remaining: '静かな水面' }),

D('choir-of-lanterns', 'Choir of Lanterns', 'front',
  { item: 'lantern', layout: 'scatter', density: 44, sweep: 'diagonal', soft: 0.16, scale: 1.6, period: 9 },
  P(34, 30, { a: 20, k: 40, mid: 48 }),
  { type: 'hold', affordance: '中央の小さな照明', feedback: '周囲の照明が徐々に同じ呼吸周期へ揃う' },
  'dropGlow',
  S('celestial', [-5, 2, 11], [-5, 2, 11], { s: 175, l: 130 }),
  { elapsed: '別の周期で発光し続ける照明', current: '同期領域', remaining: '同期していない照明' })
,

// ══ 91–100 ═══════════════════════════════════════════════════
D('star-library-whale', 'Star Library Whale', 'trail',
  { scenery: 'shelf', mark: 'shimmer', agent: 'whale', knots: 6, marks: 40, field: 34, headSize: 0.22 },
  P(240, 30, { a: 44, k: 70, mid: 42 }),
  { type: 'drag', affordance: '小さな星形の光と本棚の空いた場所', feedback: 'クジラの軌跡が星形の光へ集まる' },
  'constellation',
  S('celestial', [-24, 16], [-24, 16, 19], { s: 200, l: 165 }),
  { elapsed: '水面のように揺れた本棚', current: '半透明のクジラ', remaining: '静止した棚と星' }),

D('corridor-of-seasons', 'Corridor of Seasons', 'depth',
  { motif: 'window', layers: 12, scale: 1.05 },
  P(158, 22, { a: 120, k: 200, mid: 48 }),
  { type: 'trace', affordance: '窓の上の短い水滴または霜線', feedback: '窓の四つの質感が中央へ集まる' },
  'fleck',
  S('glass', [-5, 2], [2, -5], { s: 205, l: 175 }),
  { elapsed: '鮮明になった窓景色', current: '今いる窓', remaining: '霧でぼけた窓' }),

D('floating-island', 'Floating Island Parallax', 'depth',
  { motif: 'islands', layers: 14, scale: 1.0 },
  P(206, 20, { a: 40, k: 66, mid: 46 }),
  { type: 'hold', affordance: '中央の視点', feedback: '島のずれが少しずつ減る' },
  'arcTrail',
  S('ceramic', [-12, -5], [-12, -1], { s: 195, l: 165 }),
  { elapsed: '整列へ近づいた浮島', current: '視点の位置', remaining: 'ずれた奥行き' }),

D('gravity-garden', 'Gravity Garden', 'front',
  { item: 'fiber', layout: 'grid', density: 96, sweep: 'band', turn: -1.4, soft: 0.1, scale: 1.2 },
  P(120, 26, { a: 40, k: 62, mid: 46 }),
  { type: 'drag', affordance: '境界付近を漂う一枚の葉と中央線', feedback: '葉の上下移動が徐々に止まる' },
  'leafVein',
  S('air', [-5, 2], [2, -5, 7], { s: 165, l: 140 }),
  { elapsed: '上へ移動する葉', current: '重力反転の境界', remaining: '下へ落ちる葉' }),

D('room-on-cloud', 'Room on a Cloud', 'depth',
  { motif: 'window', layers: 9, scale: 1.2 },
  P(216, 18, { a: 40, k: 130, mid: 52 }),
  { type: 'fold', affordance: 'カーテン端と窓枠の小さな留め具', feedback: '室内へ入る光が細くなり、窓反射が強くなる' },
  'prismHex',
  S('air', [-1, 6], [6, 6, -1], { s: 190, l: 160 }),
  { elapsed: '薄い航跡と変化した雲', current: '部屋が通過している空', remaining: '手つかずの空' }),

D('mirror-city-fold', 'Mirror City Fold', 'depth',
  { motif: 'panels', layers: 12, scale: 1.0 },
  P(222, 22, { a: 30, k: 180, mid: 46 }),
  { type: 'join', affordance: '現実側と反射側の二つの対応点', feedback: '上下の輪郭が正確に一致していく' },
  'stitch',
  S('glass', [4, -8], [-8, 4], { s: 175, l: 150 }),
  { elapsed: '水面のように揺らぐ現実側', current: '入れ替わりの境界', remaining: '静かな都市と反射' }),

D('moonlight-bridge', 'Moonlight Bridge', 'trail',
  { scenery: 'star', mark: 'ripple', agent: 'dot', knots: 5, marks: 40, field: 40, headSize: 0.2 },
  P(212, 18, { a: 20, k: 40, mid: 46 }),
  { type: 'trace', affordance: '月光の先端の最後の短い線', feedback: '周囲の水面反射が線へ集まる' },
  'crescentRipple',
  S('water', [-14, 4], [4, 4, -14], { s: 180, l: 155 }),
  { elapsed: '銀色の揺れの残る水面', current: '細長い月光', remaining: '暗い水面' }),

D('inverted-waterfall', 'Inverted Waterfall', 'lines',
  { axis: 'v', density: 30, weight: 2.0 },
  P(184, 26, { a: 24, k: 44, mid: 46 }),
  { type: 'drag', affordance: '上昇する最後の水球と流れの先端', feedback: '水流が細くなり、水球へ集まる' },
  'dropGlow',
  S('water', [-17, 2], [-17, -5, 7], { s: 175, l: 150, so: { glide: 1.5 } }),
  { elapsed: '霧と水滴と濡れた反射', current: '上方向へ向かう流れ', remaining: '乾いた岩壁' }),

D('aquarium-library', 'Aquarium Library', 'fog',
  { substrate: 'shelves', sweep: 'columns', layout: 'rows', density: 60, soft: 0.1, headSize: 0.3, scale: 1.1 },
  P(198, 34, { a: 26, k: 48, mid: 42 }),
  { type: 'drag', affordance: '一匹のインク魚と本棚の縁', feedback: '魚が細長い形へ変化し、揺れが止まる' },
  'plate',
  S('underwater', [-12, -5], [-12, -5, -12], { s: 215, l: 180 }),
  { elapsed: '小さな魚が漂い出す本棚', current: '視点とインク魚', remaining: '青い霧に隠れた本棚' }),

D('kaleidoscope-garden', 'Kaleidoscope Garden', 'radial',
  { wedges: 12, radius: 0.54, cy: 0.5 },
  P(126, 34, { a: 90, k: 180, mid: 48 }),
  { type: 'hold', affordance: '万華鏡の中央', feedback: '複数の扇形レイヤーが正確な位置へ整列する' },
  'rosette',
  S('glass', [-12, 0, 12], [12, 0, 0], { s: 165, l: 150 }),
  { elapsed: '素材と奥行きの定着した領域', current: '最も鮮明な扇形', remaining: '低コントラストのぼけ' }),

// ══ history ══════════════════════════════════════════════════
D('tube', 'London Underground', 'chronicle',
  { topic: 'tube' },
  P(210, 26, { a: 18, k: 200, mid: 40 }),
  { type: 'trace', affordance: '', feedback: '' },
  'signature',
  S('glass', [-12, 0, 7], [0, 7, 12], { s: 150, l: 140 }),
  { elapsed: '開通した路線', current: '開業した年', remaining: '未開通の路線' }),

D('elements', 'The Periodic Table', 'chronicle',
  { topic: 'elements' },
  P(196, 30, { a: 30, k: 268, mid: 42 }),
  { type: 'trace', affordance: '', feedback: '' },
  'signature',
  S('ceramic', [0, 7, 12], [7, 12, 19], { s: 160, l: 150 }),
  { elapsed: '発見された元素', current: '発見の年', remaining: '空席' }),

D('emperors', 'Roman Emperors', 'chronicle',
  { topic: 'emperors' },
  P(16, 40, { a: 352, k: 40, mid: 40 }),
  { type: 'trace', affordance: '', feedback: '' },
  'signature',
  S('metal', [-12, -5, 0], [0, 5, 12], { s: 170, l: 150 }),
  { elapsed: '過ぎた治世', current: 'いまの皇帝', remaining: 'これからの五百年' }),

D('mongol', 'The Mongol Conquests', 'chronicle',
  { topic: 'mongol' },
  P(30, 34, { a: 8, k: 40, mid: 38 }),
  { type: 'trace', affordance: '', feedback: '' },
  'signature',
  S('wood', [-5, 2, 7], [2, 7, 14], { s: 165, l: 145 }),
  { elapsed: '征いた土地', current: 'その年の戦い', remaining: 'まだ届かない地' }),

D('tokaido', 'The Tokaido Road', 'chronicle',
  { topic: 'tokaido' },
  P(38, 30, { a: 40, k: 200, mid: 40 }),
  { type: 'trace', affordance: '', feedback: '' },
  'signature',
  S('fabric', [0, 5, 12], [5, 12, 17], { s: 180, l: 160 }),
  { elapsed: '歩いた宿場', current: 'いまの宿場', remaining: '京までの道' }),

// ══ painting ═════════════════════════════════════════════════
D('starry-night', 'The Starry Night', 'painting',
  { seed: 1889, subject: 'starry-night' },
  P(222, 44, { a: -170, k: -178, mid: 44 }),
  { type: 'trace', affordance: '右下の余白に署名を入れる', feedback: 'なぞった分だけ絵具が乗り、絵が仕上がる' },
  'signature',
  S('wood', [-12, -5], [-12, -5, 0], { s: 180, l: 150 }),
  { elapsed: '塗り上がった部分', current: '筆が置かれている場所', remaining: '下描きだけの生成り' }),

D('still-life-window', 'Window Still Life', 'painting',
  { seed: 20260915, subject: 'still-life' },
  P(30, 30, { a: 16, k: 32, mid: 50 }),
  { type: 'trace', affordance: '右下の余白に署名を入れる', feedback: 'なぞった分だけ絵具が乗り、絵が自分のものになる' },
  'signature',
  S('wood', [-14, -7], [-14, -7, -2], { s: 180, l: 150 }),
  { elapsed: '塗り上がった部分', current: '筆が置かれている場所', remaining: '下描きだけの生成り' })

];

// ── registry checks ──────────────────────────────────────────
// A duplicated id would silently collapse two worlds into one.
const seen = new Set();
for (const d of DESIGNS) {
  if (seen.has(d.id)) throw new Error('duplicate design id: ' + d.id);
  seen.add(d.id);
}

export const byId = (id) => DESIGNS.find((d) => d.id === id) || null;
